version: '3.8'

services:

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"
    networks:
      - rede-local 

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://n8n:5678
      N8N_HOST: n8n
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: info
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - rede-local 

  api-mcp-faculdade:
    image: davicarrano/api-mcp-faculdade:v1.1.2
    ports:
      - "8080:8080"    
    networks:
      - rede-local

networks:
  rede-local:
    driver: bridge
  

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
